### ISSUE TITLE
New thing card design

### ISSUE THREAD

**Issue by dillonfagan** [pvdthings/app#12]
The Thing cards in v0.7 only contain the thing image, with info about the thing displayed below. I'd like to play around with creating a more "integrated" card that contains the info.

**Comment by jcm427** [comment]
<img width="211" alt="Screen Shot 2023-02-21 at 8 41 20 AM" src="https://user-images.githubusercontent.com/48489157/220361864-09d61aa7-323d-4b03-b3cc-d87490b9656b.png">
