### ISSUE TITLE
Sort things by popularity or alphabetically

### ISSUE THREAD

**Issue by dillonfagan** [pvdthings/app#4]
Supporting this feature will require an API update. The Airtable base already has some sorted tables ready, they just need to be called from Glitch.

**Comment by dillonfagan** [comment]
We should have a design ready to consider for the 1/23 meeting... but not a hard deadline. @jcm427

**Comment by jcm427** [comment]
<img width="455" alt="SortByMockUp" src="https://user-images.githubusercontent.com/48489157/214307369-943ec754-a05f-4867-b60e-e762e9d0946d.png">

**Comment by cmilkaitis** [comment]
PR is up to view by popularity

**Comment by jrclinton** [comment]
Started work on the front end implementation
Will need to add a package to do this right (clsx or ClassName) so we can correctly reuse the "Chooser" dropdown component.

If there are any preferences on either comment them here.

**Comment by dillonfagan** [comment]
@jrclinton Why do we need a package to reuse the dropdown? Please elaborate
